### PR TITLE
A1 downstream vertices alternative

### PR DESCRIPTION
**Pull request by BigBadr**
complete find downstream vertices. Correct tests and 9.15 pylint.

### CODE REVIEW

**Review by milanvdzanden — APPROVED** [review]
Code looks good, Nice commenting on the main code structure this time

**Review by Halesm — APPROVED** [review]
Optimized and efficient find_downstream_vertices function and excellent unit testing for possible errors. The automatic running of black and isort helps with code formatting and saves a great amount of margin error resources upon accidental stakeholder missage.

**Review by Melgior — APPROVED** [review]
This was faster then the function we made. Looks good!

**Comment by BigBadr** [comment]
Assignment 1 is hereby completed.

**Pull request merged**
